In [4]:
!pip install -Uqq fastbook
import fastbook
fastbook.setup_book()

In [5]:
#hide
from fastbook import *
from fastai.vision.all import *

Download images of cats and dogs and train the model

In [ ]:
path = untar_data(URLs.PETS)/'images'

def is_cat(x): return x[0].isupper()

dls = ImageDataLoaders.from_name_func(path, get_image_files(path), is_cat, valid_pct=0.2, seed=42, item_tfms=Resize(224))

learn = cnn_learner(dls, resnet34, metrics=error_rate)
learn.fine_tune(1)

Test the model

In [ ]:
uploader = widgets.FileUpload()
uploader

In [ ]:
img = PILImage.create(uploader.data[0])
is_cat, _, probs = learn.predict(img)

print(f"Is this a cat: {is_cat}")
print(f"Probability its a cat: {probs[1]:.6f}")

print(f"Predictions for: {learn.dls.vocab} are: {probs[0]:.6f} {probs[1]:.6f}")

Segmentation of objects in a scene

In [30]:
path = untar_data(URLs.CAMVID_TINY)

dls = SegmentationDataLoaders.from_label_func(
    path, 
    get_image_files(path/'images'),
    label_func = lambda o: path/'labels'/f'{o.stem}_P{o.suffix}',
    bs=8,
    codes= np.loadtxt(path/'codes.txt', dtype=str))

learn = unet_learner(dls, resnet34)
learn.fine_tune(8)

Downloading: "https://download.pytorch.org/models/resnet34-333f7ec4.pth" to /home/.cache/torch/hub/checkpoints/resnet34-333f7ec4.pth

  0%|          | 0.00/83.3M [00:00<?, ?B/s]

Show resulst

In [ ]:
learn.show_results(max_n=6, figsize=(20, 50))

Movie Sentiment review

In [31]:
from fastai.text.all import *

dls = TextDataLoaders.from_folder(untar_data(URLs.IMDB), valid='test')

learn = text_classifier_learner(dls, AWD_LSTM, drop_mult=0.5, metrics=accuracy)
learn.fine_tune(4, 1e-2)

Predict the sentiment

In [32]:
print(learn.dls)
learn.predict("I really liked that movie")

<fastai.data.core.DataLoaders object at 0x7fd2853b22b0>

('pos', tensor(1), tensor([1.1240e-04, 9.9989e-01]))

In [33]:
learn.predict("Meeeh")

('pos', tensor(1), tensor([0.0589, 0.9411]))

Predict if someone is a high income earner using his social-ecoonomic background

In [34]:
from fastai.tabular.all import *

path = untar_data(URLs.ADULT_SAMPLE)

dls = TabularDataLoaders.from_csv(
    path/'adult.csv',
    path=path,
    y_names="salary",
    cat_names = ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race'],
    cont_names = ['age', 'fnlwgt', 'education-num'],
    procs = [Categorify, FillMissing, Normalize])

learn = tabular_learner(dls, metrics=accuracy)
learn.fit_one_cycle(3)

Show the results

In [36]:
learn.show_results()

Movie recommndedation system

In [6]:
from fastai.collab import *

path = untar_data(URLs.ML_SAMPLE)

dls = CollabDataLoaders.from_csv(path/'ratings.csv')

learn = collab_learner(dls, y_range=(0.5, 5.5))
learn.fine_tune(10)

Show results

In [7]:
learn.show_results()